[settings.kubernetes]
cluster-domain = "cluster.local"
standalone-mode = false
authentication-mode = "tls"
pod-infra-container-image = "k8s.gcr.io/pause:3.2"
server-tls-bootstrap = false
cloud-provider = "external"

api-server = "https://192.168.128.201:6443"
cluster-dns-ip = "192.168.128.201"
bootstrap-token = "zfxyjm.7k9ar5dreydfv4js"
cluster-certificate = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJRENDQWdpZ0F3SUJBZ0lRWG10TWhpeklKRjVBZ0tKL0FaU2VBakFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVJBd0RnWURWUVFLRXdkMGVYQm9iMjl1TVJZd0ZBWURWUVFERXcxcmRXSmxjbTVsZEdWekxXTmhNQjRYRFRJeApNVEF5TkRFek16SXlOVm9YRFRJeU1UQXlOREV6TXpJeU5Wb3dLakVRTUE0R0ExVUVDaE1IZEhsd2FHOXZiakVXCk1CUUdBMVVFQXhNTmEzVmlaWEp1WlhSbGN5MWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTlZ3Skp2eFk0RWV3WnZVVlhQMHFGTFdzbTQ3aVZRcFVxQnAwNEZReDcwYTNHNTlrRng5dGU2MApzY2Y5elRQVHNxYXlGdTExZHVwQzBhRjA1aFhjaERyWnU0ZG1WZFB3eTZ5OUJMT2VhVXFpZlYrMjdsZ3pmcHZWClcyNnlLcHVxVzNFWlFsbStFUVY3TG1CdUlyMXVabS9oMnAvUEx2OVh6S3gzWU5yek1OVTVrZEZHVVRVSWRvYlkKZlJtZFNZcjZ3RW00SWM0K0JMbmI4KzVCTFBmY00yNGJpa3NrVFFuL1FvRmdJMTdqU1JnVm1WS3RUQ0dtQzZ1NwpodGlpNEhxS3N0NVFFN1o0NEhja0VGcFBTeVpaenNQV3BHZ0NncnFSamJGczUvVWp1cFFPKy9nY3VDS3pvaHM2CkpkelNKd21PZktVWVhWeWxGYkVnbEI0TnJTT1lVcGtDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkYxNFlKcWpxMytnczdjNlk2d2N6MEhvS3pkUApNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJvdDdtMUMxQlh2N3Z6RDBMMjQxSCtQNTdtWmE1YXhyY0pQcXl0CnEzblZ6MVQ0SFFRV1c0QUJySVZMM2lPUlZndjZtUmFHbGNvOHJTdkJXeFVIWjdzMXJ3ZE5XZE95UFlnSVJFeDQKbncyUGE4eTYxaFYrZXVYNE5vVkxvYTIxWkZvek1VYUc0eUM2K3Mzclo1MVdINWNObGl1ZGdKNWQ5bisyc3FpbAphN3dCT0tLNUZrWTVLUTVFUWt5SWwvM2N3YWtsa2dvb3AyUFU2TlZoNGMySHhaeEdONDNHeWdWL0VocFZXT0IzCkJiczhQU01LR0NzL0NFTzR1czdTZ1FMclpZUVMzNzNrT1ExTnZvTjgveHk4K0lGNW0rUTZKbEtXdE1ZcFN5RGUKWk9BR1lzdVZ2bFBGWHNKektOOHpENWhyQUpNR0NQdXJNZFB5K0gwa1JTYjhhSk9YCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"

[metadata.settings.kubernetes]
node-ip.setting-generator = "netdog node-ip"
affected-services = ["kubernetes"]

# Metrics
[settings.metrics]
service-checks = ["apiserver", "chronyd", "containerd", "host-containerd", "kubelet", "vmtoolsd"]

# Network
[metadata.settings.network]
affected-services = ["containerd", "kubernetes", "host-containerd", "host-containers"]
