[package]
name = "libglib"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://download.gnome.org/sources/glib"

[[package.metadata.build-package.external-files]]
url = "https://download.gnome.org/sources/glib/2.70/glib-2.70.1.tar.xz"
sha512 = "639317c98ab72ad853608ab4d395484daff135c0222556c51ca93fd8533c5759db14478beda964e4feb02bb2737a46a4eda25063f98a9c6ba6ae4bc5d74bf5e1"

[[package.metadata.build-package.external-files]]
url = "https://downloads.sourceforge.net/pcre/pcre-8.37.tar.bz2"
sha512 = "19344c9add2ebbd26c528505d07d3b028d79bc3e6103d51453a449cebd76bc76f5bc7ddd9ef0de41f98c50be74a2d9a65db539ed60f1add1086d99bde8a81466"

[[package.metadata.build-package.external-files]]
url = "https://wrapdb.mesonbuild.com/v2/pcre_8.37-2/get_patch"
path = "pcre_8.37-2_patch.zip"
sha512 = "601790189ce5553b71931f6eec2bb167f74de53736e84b68fd5e1d8658661b3239782ac9c4cd1eb8c87fbbcdb49f5cd6954d6f48d47c6ef8895ee55bc70f15b8"

[build-dependencies]
glibc = { path = "../glibc" }
libffi = { path = "../libffi" }
libselinux = { path = "../libselinux" }
libz = { path = "../libz" }
util-linux = { path = "../util-linux" }
